
project_id = "qsecdncdiykzuimtaosp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.send-report-email]
verify_jwt = false

[functions.increment-counter]
verify_jwt = false

[functions.tracking]
verify_jwt = false

[functions.test-email-direct]
verify_jwt = false

[functions.test-email-providers]
verify_jwt = false

[functions.test-resend]
verify_jwt = false
