// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otmzptugrbxrfimkzkwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90bXpwdHVncmJ4cmZpbWt6a3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTY3NTQsImV4cCI6MjA2MDM5Mjc1NH0.1x19oXoE35uYnn3VWqVmy_O2VZ885WVSEUyrJyTXroY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);